


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_configuration" (
    "id" bigint NOT NULL,
    "category" character varying(255),
    "parameter" character varying(255),
    "value" character varying(255)
);


ALTER TABLE "public"."app_configuration" OWNER TO "postgres";


ALTER TABLE "public"."app_configuration" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_configuration_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."app_user" (
    "id" bigint NOT NULL,
    "password" character varying(255) NOT NULL,
    "totp_secret" character varying(255),
    "username" character varying(255) NOT NULL
);


ALTER TABLE "public"."app_user" OWNER TO "postgres";


ALTER TABLE "public"."app_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."app_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."category" (
    "id" bigint NOT NULL,
    "description" character varying(255),
    "name" character varying(255) NOT NULL,
    "type" character varying(255) NOT NULL
);


ALTER TABLE "public"."category" OWNER TO "postgres";


ALTER TABLE "public"."category" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."expense" (
    "payment_mode" character varying(255),
    "id" bigint NOT NULL
);


ALTER TABLE "public"."expense" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."income" (
    "source" character varying(255),
    "id" bigint NOT NULL
);


ALTER TABLE "public"."income" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."item" (
    "id" bigint NOT NULL,
    "description" character varying(255),
    "name" character varying(255) NOT NULL,
    "subcategory" bigint NOT NULL
);


ALTER TABLE "public"."item" OWNER TO "postgres";


ALTER TABLE "public"."item" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."revolving" (
    "closed" boolean NOT NULL,
    "is_give" boolean NOT NULL,
    "id" bigint NOT NULL
);


ALTER TABLE "public"."revolving" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."saving" (
    "id" bigint NOT NULL,
    "is_in" boolean
);


ALTER TABLE "public"."saving" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sub_category" (
    "id" bigint NOT NULL,
    "description" character varying(255),
    "name" character varying(255) NOT NULL,
    "category" bigint NOT NULL
);


ALTER TABLE "public"."sub_category" OWNER TO "postgres";


ALTER TABLE "public"."sub_category" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sub_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transaction" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "description" character varying(255) NOT NULL,
    "imported" boolean,
    "notes" "text",
    "reference_number" character varying(255),
    "transaction_time" timestamp(6) without time zone NOT NULL,
    "value" double precision NOT NULL,
    "category" bigint,
    "item" bigint,
    "subcategory" bigint
);


ALTER TABLE "public"."transaction" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."transaction_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."transaction_seq" OWNER TO "postgres";


ALTER TABLE ONLY "public"."app_configuration"
    ADD CONSTRAINT "app_configuration_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."app_user"
    ADD CONSTRAINT "app_user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."category"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expense"
    ADD CONSTRAINT "expense_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."income"
    ADD CONSTRAINT "income_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."revolving"
    ADD CONSTRAINT "revolving_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saving"
    ADD CONSTRAINT "saving_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sub_category"
    ADD CONSTRAINT "sub_category_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "transaction_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."app_user"
    ADD CONSTRAINT "uk3k4cplvh82srueuttfkwnylq0" UNIQUE ("username");



ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "uk6uy2b062fforbiwnnuhemudi1" UNIQUE ("name", "subcategory");



ALTER TABLE ONLY "public"."sub_category"
    ADD CONSTRAINT "ukpy7r0guxpxw7rth91nm344wst" UNIQUE ("name", "category");



ALTER TABLE ONLY "public"."sub_category"
    ADD CONSTRAINT "fk4owrd52c0jsrpq9k19xtf6tyj" FOREIGN KEY ("category") REFERENCES "public"."category"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."revolving"
    ADD CONSTRAINT "fk5yxl9i7pmgibdx9xpsurkc409" FOREIGN KEY ("id") REFERENCES "public"."transaction"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saving"
    ADD CONSTRAINT "fk85a57nmrljbak4rlailmo13tk" FOREIGN KEY ("id") REFERENCES "public"."transaction"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "fkdwb4581n08uwbmw45v2fu3wur" FOREIGN KEY ("subcategory") REFERENCES "public"."sub_category"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "fkjiglaqkek73xo69bdi9b4vuwp" FOREIGN KEY ("item") REFERENCES "public"."item"("id");



ALTER TABLE ONLY "public"."income"
    ADD CONSTRAINT "fko0cqlyxhy7geulnuli8hidwc8" FOREIGN KEY ("id") REFERENCES "public"."transaction"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."expense"
    ADD CONSTRAINT "fkpjkh4g79gl5arx0oyjdy63ymy" FOREIGN KEY ("id") REFERENCES "public"."transaction"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "fkspqsxcbsgpqpaj1lapag6kcfl" FOREIGN KEY ("subcategory") REFERENCES "public"."sub_category"("id");



ALTER TABLE ONLY "public"."transaction"
    ADD CONSTRAINT "fkssg9rm9g39u5bf093hnhuk8vb" FOREIGN KEY ("category") REFERENCES "public"."category"("id");



ALTER TABLE "public"."app_configuration" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."app_user" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."category" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expense" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."income" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."item" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."revolving" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."saving" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sub_category" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transaction" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "anon";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";


















GRANT ALL ON TABLE "public"."app_configuration" TO "anon";
GRANT ALL ON TABLE "public"."app_configuration" TO "authenticated";
GRANT ALL ON TABLE "public"."app_configuration" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_configuration_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_configuration_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_configuration_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."app_user" TO "anon";
GRANT ALL ON TABLE "public"."app_user" TO "authenticated";
GRANT ALL ON TABLE "public"."app_user" TO "service_role";



GRANT ALL ON SEQUENCE "public"."app_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."app_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."app_user_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."category" TO "anon";
GRANT ALL ON TABLE "public"."category" TO "authenticated";
GRANT ALL ON TABLE "public"."category" TO "service_role";



GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."expense" TO "anon";
GRANT ALL ON TABLE "public"."expense" TO "authenticated";
GRANT ALL ON TABLE "public"."expense" TO "service_role";



GRANT ALL ON TABLE "public"."income" TO "anon";
GRANT ALL ON TABLE "public"."income" TO "authenticated";
GRANT ALL ON TABLE "public"."income" TO "service_role";



GRANT ALL ON TABLE "public"."item" TO "anon";
GRANT ALL ON TABLE "public"."item" TO "authenticated";
GRANT ALL ON TABLE "public"."item" TO "service_role";



GRANT ALL ON SEQUENCE "public"."item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."item_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."revolving" TO "anon";
GRANT ALL ON TABLE "public"."revolving" TO "authenticated";
GRANT ALL ON TABLE "public"."revolving" TO "service_role";



GRANT ALL ON TABLE "public"."saving" TO "anon";
GRANT ALL ON TABLE "public"."saving" TO "authenticated";
GRANT ALL ON TABLE "public"."saving" TO "service_role";



GRANT ALL ON TABLE "public"."sub_category" TO "anon";
GRANT ALL ON TABLE "public"."sub_category" TO "authenticated";
GRANT ALL ON TABLE "public"."sub_category" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sub_category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sub_category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sub_category_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transaction" TO "anon";
GRANT ALL ON TABLE "public"."transaction" TO "authenticated";
GRANT ALL ON TABLE "public"."transaction" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transaction_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transaction_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transaction_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



































drop extension if exists "pg_net";


