CREATE TABLE IF NOT EXISTS public.trusted_browser (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       varchar(255) NOT NULL UNIQUE,
    username    varchar(255) NOT NULL,
    expires_at  timestamp    NOT NULL
);
ALTER TABLE public.trusted_browser ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."trusted_browser" TO "anon";
GRANT ALL ON TABLE "public"."trusted_browser" TO "authenticated";
GRANT ALL ON TABLE "public"."trusted_browser" TO "service_role";
